# .github/workflows/gameci.yml

name: main

on:
  push:
    branches:
      - main # Update this to match the branch you want to trigger the workflow on

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Unity
      run: |
        curl -sSL https://game.ci/api/installer | bash -s -- --yes --branch ${{ env.UNITY_VERSION }} --install-location /opt/unity

    - name: Build and Test
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }} # Add your Unity license as a secret in your GitHub repository
        UNITY_PROJECT_PATH: "URP_ShortCI" # Update this to match your Unity project path
        UNITY_VERSION: "2021.2.0f1" # Update this to match the Unity version you want to use
      run: |
        export UNITY_LICENSE="$UNITY_LICENSE"
        export UNITY_PROJECT_PATH="$UNITY_PROJECT_PATH"
        export UNITY_VERSION="$UNITY_VERSION"
        curl -sSL https://game.ci/api/runner | bash -s -- --project-path "$UNITY_PROJECT_PATH" --unity-version "$UNITY_VERSION" --execute build,test
